fix linter and formating issues

diff --git a/rootfs/etc/cont-init.d/50-vrs b/rootfs/etc/cont-init.d/50-vrs
--- a/rootfs/etc/cont-init.d/50-vrs
+++ b/rootfs/etc/cont-init.d/50-vrs
@@ -1,5 +1,5 @@
 #!/usr/bin/with-contenv bash
-#shellcheck shell=bash disable=SC2034
+#shellcheck shell=bash disable=SC2034,SC2164
 
 APPNAME="$(hostname)/vrs-init"
 VRS_DIR="/opt/vrs"
@@ -46,19 +46,19 @@ mkdir -p "${VRS_CONFIG_DIR}/CustomContent/CustomInjectedFiles"
 
 #download and install pre-filled DB for operator flags. As this should only happen once, no commit id check needed
 if [ ! -e "${VRS_CONFIG_DIR}/db/BaseStation.sqb" ]
+then
+  echo "[$APPNAME][$(date)] Downloading database for Operator Flags"
+  if curl --compressed -s -L -o "${VRS_CONFIG_DIR}/BaseStation.zip" ${FLAGSDB_LINK} && unzip -qq -o -d "${VRS_CONFIG_DIR}/db" "${VRS_CONFIG_DIR}/BaseStation.zip"
   then
-    echo "[$APPNAME][$(date)] Downloading database for Operator Flags"
-    if curl --compressed -s -L -o "${VRS_CONFIG_DIR}/BaseStation.zip" ${FLAGSDB_LINK} && unzip -qq -o -d "${VRS_CONFIG_DIR}/db" "${VRS_CONFIG_DIR}/BaseStation.zip"
-      then
-        echo "[$APPNAME][$(date)] Database for Operator Flags installed successfully"
-        #that should prevent a DB update right after a fresh download
-        PROBE_SQB=$(curl -sH "Accept: application/vnd.github.v3+json" $WHICHREPO_SQB | awk  "c&&!--c;/$WHICHBRANCH_SQB/{c=2}" | awk '/"sha"/ { print $2}' | sed 's/"//g;s/.$//g')
-        echo "$PROBE_SQB" > $ACTUALFILE_SQB
-        echo "[$APPNAME][$(date)] Updated $ACTUALFILE_SQB to commit ID $PROBE_SQB"
-      else
-        echo "[$APPNAME][$(date)] Database for Operator Flags not installed - failure"
-    fi
+    echo "[$APPNAME][$(date)] Database for Operator Flags installed successfully"
+    #that should prevent a DB update right after a fresh download
+    PROBE_SQB=$(curl -sH "Accept: application/vnd.github.v3+json" $WHICHREPO_SQB | awk  "c&&!--c;/$WHICHBRANCH_SQB/{c=2}" | awk '/"sha"/ { print $2}' | sed 's/"//g;s/.$//g')
+    echo "$PROBE_SQB" > $ACTUALFILE_SQB
+    echo "[$APPNAME][$(date)] Updated $ACTUALFILE_SQB to commit ID $PROBE_SQB"
   else
+    echo "[$APPNAME][$(date)] Database for Operator Flags not installed - failure"
+  fi
+else
     echo "[$APPNAME][$(date)] Found an existing DB in $VRS_CONFIG_DIR, not touching anything!"
 fi
 
@@ -67,14 +67,15 @@ fi
 # If it hasn't, a username / password and a bunch of other files will be created...
 #    ...and VRS will actually stay up and run. We will shut it down after a max runtime of $MAXTIME secs.
 if [ ! -e "${VRS_CONFIG_DIR}/Configuration.xml" ]
-  then
-    echo "[$APPNAME][$(date)] No Configuration.xml found, doing first run initialization."
-    cd "${VRS_DIR}"
-    echo "[$APPNAME][$(date)] Starting ${VRS_DIR}/${VRS_EXEC} ${VRS_CMDLINE[@]}"
-    timeout "$MAXTIME" exec ${VRS_EXEC} "${VRS_CMDLINE[@]}" >/dev/null 2>&1
-    echo "[$APPNAME][$(date)] Virtual Radar Server has been initialized."
-  else
-    echo "[$APPNAME][$(date)] Configuration.xml found, skipping initialization."
+then
+  echo "[$APPNAME][$(date)] No Configuration.xml found, doing first run initialization."
+  cd "${VRS_DIR}"
+  echo "[$APPNAME][$(date)] Starting ${VRS_DIR}/${VRS_EXEC} ${VRS_CMDLINE[*]}"
+  # shellcheck disable=SC2068,SC2086
+  timeout "$MAXTIME" exec ${VRS_EXEC} ${VRS_CMDLINE[@]} >/dev/null 2>&1
+  echo "[$APPNAME][$(date)] Virtual Radar Server has been initialized."
+else
+  echo "[$APPNAME][$(date)] Configuration.xml found, skipping initialization."
 fi
 
 # Replace 127.0.0.1 With ReadSB
@@ -82,30 +83,31 @@ sed -i 's#<Address>127.0.0.1</Address>#<Address>readsb</Address>#g' "${VRS_CONFI
 
 #Injecting settings for silhouettes, OpFlags and DB into Configuration.xml
 if ! grep -q "<DatabaseFileName>" "${VRS_CONFIG_DIR}/Configuration.xml"
-  then
-    sed -i "/^  <BaseStationSettings>.*/a \    \<DatabaseFileName>/root/.local/share/VirtualRadar/db/BaseStation.sqb</DatabaseFileName>" "${VRS_CONFIG_DIR}/Configuration.xml"
-    echo "[$APPNAME][$(date)] Added database filename to Configuration.xml"
-  else
-    echo "[$APPNAME][$(date)] DatabaseFileName found, not touching config."
+then
+  sed -i "/^  <BaseStationSettings>.*/a \    \<DatabaseFileName>/root/.local/share/VirtualRadar/db/BaseStation.sqb</DatabaseFileName>" "${VRS_CONFIG_DIR}/Configuration.xml"
+  echo "[$APPNAME][$(date)] Added database filename to Configuration.xml"
+else
+  echo "[$APPNAME][$(date)] DatabaseFileName found, not touching config."
 fi
 
 if ! grep -q "<OperatorFlagsFolder>" "${VRS_CONFIG_DIR}/Configuration.xml"
-  then
-    sed -i "/^  <BaseStationSettings>.*/a \    \<OperatorFlagsFolder>/root/.local/share/VirtualRadar/flags</OperatorFlagsFolder>" "${VRS_CONFIG_DIR}/Configuration.xml"
-    echo "[$APPNAME][$(date)] Added Operator Flags folder to Configuration.xml"
-  else
-    echo "[$APPNAME][$(date)] OperatorFlagsFolder found, not touching config."
+then
+  sed -i "/^  <BaseStationSettings>.*/a \    \<OperatorFlagsFolder>/root/.local/share/VirtualRadar/flags</OperatorFlagsFolder>" "${VRS_CONFIG_DIR}/Configuration.xml"
+  echo "[$APPNAME][$(date)] Added Operator Flags folder to Configuration.xml"
+else
+  echo "[$APPNAME][$(date)] OperatorFlagsFolder found, not touching config."
 fi
 
 if ! grep -q "<SilhouettesFolder>" "${VRS_CONFIG_DIR}/Configuration.xml"
-  then
-    sed -i "/^  <BaseStationSettings>.*/a \    \<SilhouettesFolder>/root/.local/share/VirtualRadar/silhouettes</SilhouettesFolder>" "${VRS_CONFIG_DIR}/Configuration.xml"
-    echo "[$APPNAME][$(date)] Added Silhouettes folder to Configuration.xml"
-  else
-    echo "[$APPNAME][$(date)] SilhouettesFolder found, not touching config."
-    fi
+then
+  sed -i "/^  <BaseStationSettings>.*/a \    \<SilhouettesFolder>/root/.local/share/VirtualRadar/silhouettes</SilhouettesFolder>" "${VRS_CONFIG_DIR}/Configuration.xml"
+  echo "[$APPNAME][$(date)] Added Silhouettes folder to Configuration.xml"
+else
+  echo "[$APPNAME][$(date)] SilhouettesFolder found, not touching config."
+fi
+
 #cleanup and exit
-[[ -f "${VRS_CONFIG_DIR}/BaseStation.zip" ]] && rm -f "${VRS_CONFIG_DIR}/BaseStation.zip"
+[[ -f "${VRS_CONFIG_DIR}/BaseStation.zip" ]] && rm -f "${VRS_CONFIG_DIR}/BaseStation.zip" || true
 echo "[$APPNAME][$(date)] Cleaned up downloaded files."
 echo "[$APPNAME][$(date)] Finished basic configuration."
 
