set-up of api keys added

diff --git a/rootfs/etc/cont-init.d/61-layer b/rootfs/etc/cont-init.d/61-layer
--- a/rootfs/etc/cont-init.d/61-layer
+++ b/rootfs/etc/cont-init.d/61-layer
@@ -56,6 +56,18 @@ if [[ -n "${VRS_ENHANCED_LAYERS_COUNTRY}" ]]
                 else
                   echo "[$APPNAME][$(date)] Enhanced Layers config enabled - Failure"
               fi
+           if ! [[ -n "${VRS_ENHANCED_LAYERS_OPENAIP_APIKEY}" || "${VRS_ENHANCED_LAYERS_OPENWX_APIKEY}" ]]
+             then
+               echo "[$APPNAME][$(date)] VRS_ENHANCED_LAYERS_OPENAIP_APIKEY and VRS_ENHANCED_LAYERS_OPENWC_APIKEY not set. Expect those layers not to work."
+             else
+               if sed -i -e "s/##OPENWXAPIKEY##/${VRS_ENHANCED_LAYERS_OPENWX_APIKEY}/g" ${VRS_EXTENSION_DIR}/EndOfBody.html &&\
+                 sed -i -e "s/##OPENAIPKEY##/${VRS_ENHANCED_LAYERS_OPENAIP_APIKEY}/g" ${VRS_EXTENSION_DIR}/EndOfBody.html
+                 then
+                   echo "[$APPNAME][$(date)] Enhanced Layers API Keys config injection - OK"
+                 else
+                   echo "[$APPNAME][$(date)] Enhanced Layers API Keys config injection - Failure"
+               fi
+           fi
         else        
           echo "[$APPNAME][$(date)] Enhanced Layers archive download and uncompress - Failure"
       fi
