fixes for shellcheck

diff --git a/rootfs/etc/cont-init.d/61-layer b/rootfs/etc/cont-init.d/61-layer
--- a/rootfs/etc/cont-init.d/61-layer
+++ b/rootfs/etc/cont-init.d/61-layer
@@ -2,7 +2,7 @@
 # shellcheck shell=bash
 
 APPNAME="$(hostname)/vrs-cclayer"
-VRS_DIR="/opt/vrs"
+#VRS_DIR="/opt/vrs"
 VRS_CONFIG_DIR="/root/.local/share/VirtualRadar"
 VRS_EXTENSION_DIR="/root/.local/share/VirtualRadar/CustomContent/CustomInjectedFiles"
 
@@ -40,16 +40,16 @@ if [[ -n "${VRS_ENHANCED_LAYERS_COUNTRY}" ]]
           echo "[$APPNAME][$(date)] Enhanced Layers archive download and uncompress - OK"
             case "${VRS_ENHANCED_LAYERS_COUNTRY,,}" in
               (uk) echo "[$APPNAME][$(date)] Enhanced Layers renaming country files for: ${VRS_ENHANCED_LAYERS_COUNTRY}"
-                rename -f 's/UK//' *.geojson
+                rename -f 's/UK//' -- *.geojson
                 ;;
               (de) echo "[$APPNAME][$(date)] Enhanced Layers renaming country files for: ${VRS_ENHANCED_LAYERS_COUNTRY}"
-                rename -f 's/DE//' *.geojson
+                rename -f 's/DE//' -- *.geojson
                 ;;
               (usa1) echo "[$APPNAME][$(date)] Enhanced Layers renaming country files for: ${VRS_ENHANCED_LAYERS_COUNTRY}"
-                rename -f 's/USA1//' *.geojson
+                rename -f 's/USA1//' -- *.geojson
                 ;;
               (se) echo "[$APPNAME][$(date)] Enhanced Layers renaming country files for: ${VRS_ENHANCED_LAYERS_COUNTRY}"
-                rename -f 's/SE//' *.geojson
+                rename -f 's/SE//' -- *.geojson
                 ;;
               (*) echo "[$APPNAME][$(date)] Unknown or wrong country, default set to UK"
                 ;;
@@ -63,18 +63,18 @@ if [[ -n "${VRS_ENHANCED_LAYERS_COUNTRY}" ]]
                 else
                   echo "[$APPNAME][$(date)] Enhanced Layers config enabled - Failure"
               fi
-           if ! [[ -n "${VRS_ENHANCED_LAYERS_OPENAIP_APIKEY}" || "${VRS_ENHANCED_LAYERS_OPENWX_APIKEY}" ]]
-             then
-               echo "[$APPNAME][$(date)] VRS_ENHANCED_LAYERS_OPENAIP_APIKEY and VRS_ENHANCED_LAYERS_OPENWX_APIKEY not set. Expect those layers not to work."
-             else
-               if sed -i -e "s/##OPENWXAPIKEY##/${VRS_ENHANCED_LAYERS_OPENWX_APIKEY}/g" ${VRS_EXTENSION_DIR}/EndOfBody.html &&\
-                 sed -i -e "s/##OPENAIPKEY##/${VRS_ENHANCED_LAYERS_OPENAIP_APIKEY}/g" ${VRS_EXTENSION_DIR}/EndOfBody.html
-                 then
-                   echo "[$APPNAME][$(date)] Enhanced Layers API Keys config injection - OK"
-                 else
-                   echo "[$APPNAME][$(date)] Enhanced Layers API Keys config injection - Failure"
-               fi
-           fi
+            if ! [[ -n "${VRS_ENHANCED_LAYERS_OPENAIP_APIKEY}" || "${VRS_ENHANCED_LAYERS_OPENWX_APIKEY}" ]]
+              then
+                echo "[$APPNAME][$(date)] VRS_ENHANCED_LAYERS_OPENAIP_APIKEY and VRS_ENHANCED_LAYERS_OPENWX_APIKEY not set. Expect those layers not to work."
+              else
+                if sed -i -e "s/##OPENWXAPIKEY##/${VRS_ENHANCED_LAYERS_OPENWX_APIKEY}/g" ${VRS_EXTENSION_DIR}/EndOfBody.html &&\
+                  sed -i -e "s/##OPENAIPKEY##/${VRS_ENHANCED_LAYERS_OPENAIP_APIKEY}/g" ${VRS_EXTENSION_DIR}/EndOfBody.html
+                  then
+                    echo "[$APPNAME][$(date)] Enhanced Layers API Keys config injection - OK"
+                  else
+                    echo "[$APPNAME][$(date)] Enhanced Layers API Keys config injection - Failure"
+                fi
+            fi
         else        
           echo "[$APPNAME][$(date)] Enhanced Layers archive download and uncompress - Failure"
       fi
